spring.application.name=clients
spring.datasource.url=${CLIENTS_URL}
spring.datasource.username=${CLIENTS_USER}
spring.datasource.password=${CLIENTS_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true